import { expect, test } from '@playwright/test';

/**
 * Highest-risk playground invariant (RELEASE.md → Go/no-go gate #2, SEC-10..13):
 * the browser refuses cross-origin requests from sandboxed code even if the
 * in-Worker fetch shim is bypassed. The backstop is the CSP `connect-src 'self'`.
 *
 * These specs are deliberately UI-independent (no CodeMirror / run-button
 * driving) so they prove the *security model*, not the playground chrome.
 */

test.describe('playground sandbox CSP', () => {
    test('document policy confines egress and keeps eval out of the page', async ({
        page,
    }) => {
        const res = await page.goto('/');
        expect(res, 'home route should respond').toBeTruthy();

        const csp = res!.headers()['content-security-policy'];
        expect(csp, 'a CSP must be served').toBeTruthy();

        // The egress backstop — holds in dev and prod.
        expect(csp).toContain("connect-src 'self'");
        // Workers are allowed (same-origin + blob).
        expect(csp).toContain("worker-src 'self' blob:");

        // eval-confinement is a *production* property: dev relaxes script-src
        // for Fast Refresh (detectable via the HMR websocket relaxation). In a
        // prod build the document must NOT be able to eval — that stays confined
        // to the sandbox Worker, which carries its own policy (next test).
        const isDev = csp!.includes('ws:');
        if (isDev) {
            test.info().annotations.push({
                type: 'note',
                description:
                    'dev server: eval-confinement relaxed for Fast Refresh — run against `pnpm build && pnpm start` to assert it',
            });
        } else {
            expect(csp).not.toContain("'unsafe-eval'");
        }
    });

    test('the sandbox Worker script may eval but stays same-origin', async ({
        request,
    }) => {
        const res = await request.get('/sandbox/sandbox-worker.mjs');
        // The bundle is generated by `build:sandbox`; if absent the route still
        // matches the /sandbox/* header rule, so the CSP assertion holds.
        const csp = res.headers()['content-security-policy'];
        expect(csp, 'worker script must carry its own CSP').toBeTruthy();
        expect(csp).toContain("'unsafe-eval'"); // eval is allowed *here*
        expect(csp).toContain("connect-src 'self'"); // but egress is not
    });

    test('a Worker cannot fetch a cross-origin URL (CSP backstop)', async ({
        page,
    }) => {
        await page.goto('/');

        // Fail loudly if any request to the foreign origin actually leaves.
        const leaked: string[] = [];
        page.on('request', (r) => {
            if (new URL(r.url()).origin === 'https://example.org') {
                leaked.push(r.url());
            }
        });

        // Spin a blob Worker (allowed by worker-src 'self' blob:) that inherits
        // the document CSP and try to reach a foreign origin from inside it.
        const verdict = await page.evaluate(async () => {
            const src = `
                self.onmessage = async () => {
                    try {
                        await fetch('https://example.org/');
                        self.postMessage('ALLOWED');
                    } catch (e) {
                        self.postMessage('BLOCKED:' + (e && e.name));
                    }
                };`;
            const url = URL.createObjectURL(
                new Blob([src], { type: 'application/javascript' }),
            );
            const w = new Worker(url);
            return await new Promise<string>((resolve) => {
                w.onmessage = (e) => resolve(String(e.data));
                w.postMessage('go');
            });
        });

        expect(
            verdict,
            'worker fetch to a foreign origin must be blocked',
        ).toContain('BLOCKED');
        expect(
            leaked,
            'no request to the foreign origin may leave',
        ).toHaveLength(0);
    });

    test('the playground page still renders under the strict CSP', async ({
        page,
    }) => {
        const res = await page.goto('/playground');
        expect(res?.status(), 'playground route should 200').toBe(200);
        // No CSP violation should blank the app — the document body has content.
        await expect(page.locator('body')).not.toBeEmpty();
    });
});
